### ISSUE TITLE
Prohibit sending forms multiple times

### ISSUE THREAD

**Issue by svenseeberg** [netzbegruenung/keycloak-2fa-sms-authenticator#30]
It is possible for users to hit the submit button multiple times when entering a code. This results in an error page for users, because usually for the second request the CSRF token has expired.

We should disable the submit action after it has been triggered once.

**Comment by svenseeberg** [comment]
Okay, in this case we need to investigate if this a bug with Keycloak in general.

**Comment by svenseeberg** [comment]
> Please note, this also applies to TOTP.

I could not reproduce this problem for the TOTP form.

**Comment by b90g** [comment]
same here, FF/Chromium 104. sorry for the hassle.

**Comment by melegiul** [comment]
I can not reproduce this for the SMS plugin with firefox 91.13.0esr, too.
I see the "invalid page" error with chrome 104.0.5112.101, but only when I try login to wolke and not directly to saml.
So does using firefox as work around solve this for you, too?
