### ISSUE TITLE
Put 6 digit code first

### ISSUE THREAD

**Issue by b90g** [netzbegruenung/keycloak-2fa-sms-authenticator#58]
https://github.com/netzbegruenung/keycloak-2fa-sms-authenticator/blob/b18604f29a254d0d5a376cac99f9fa4defed916b/src/main/resources/theme-resources/messages/messages_de.properties#L1

Message previews allow many users to just type the 6 digit code from their phone from message preview, whereas right now the digit code is to late in the message text and not shown in preview anymore:

https://helpdesk.verdigado.com/#ticket/zoom/80807/122860

![grafik](https://user-images.githubusercontent.com/63392812/212259898-63bb3c19-d5ed-4585-b34f-01c3f74056f0.png)

Neuerdings wird auch von Apple der Code nicht mehr erkannt melden Anwender*innen im chat:

Früher:

`Ihr Grünes Netz SMS Code lautet 738269 und ist gültig für 15 Minuten.`

Jetzt:

`Ihr Grünes Netz SMS ist 961640 und ist gültig für 15 Minuten.`

https://chatbegruenung.de/channel/chatbegruenung?msg=XBbNPWeLHZwpJNhm5

**Comment by svenseeberg** [comment]
Not part of the plugin. Moved to theme repo.
