### ISSUE TITLE
Integrate form into Account Security

### ISSUE THREAD

**Issue by svenseeberg** [netzbegruenung/keycloak-2fa-sms-authenticator#6]
We want a phone number form next to the Webauthn and TOTP configuration for users.

This is currently "blocked" by https://github.com/keycloak/keycloak/issues/12709

**Comment by melegiul** [comment]
Maybe relevant: https://www.keycloak.org/docs/latest/server_development/#_theme_resource
There it says:
> When implementing custom providers in Keycloak there may often be a need to add additional templates, resources and messages bundles.
> An example use-case would be a [custom authenticator](https://www.keycloak.org/docs/latest/server_development/#_auth_spi) that requires additional templates and resources.

I will try this next.
